import type { Metadata } from "next";
import Link from "next/link";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Terms of Service — LeadScan",
  description: "Terms of Service for LeadScan — company intelligence platform.",
};

const LAST_UPDATED = "June 7, 2025";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 44 }}>
      <h2 style={{ fontSize: 18, fontWeight: 700, letterSpacing: "-0.015em", margin: "0 0 14px", color: "#fafafa" }}>
        {title}
      </h2>
      <div style={{ fontSize: 14, color: "#a1a1aa", lineHeight: 1.85 }}>
        {children}
      </div>
    </section>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <p style={{ margin: "0 0 14px" }}>{children}</p>;
}

function Ul({ items }: { items: string[] }) {
  return (
    <ul style={{ margin: "0 0 14px", paddingLeft: 22, display: "flex", flexDirection: "column", gap: 6 }}>
      {items.map((item, i) => (
        <li key={i} style={{ paddingLeft: 6 }}>{item}</li>
      ))}
    </ul>
  );
}

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main style={{ minHeight: "calc(100vh - 62px)" }}>
        <div style={{ maxWidth: 740, margin: "0 auto", padding: "64px 20px 100px" }}>

          {/* Header */}
          <div style={{ marginBottom: 52 }}>
            <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: "0.1em", color: "#3b82f6", textTransform: "uppercase", margin: "0 0 14px" }}>Legal</p>
            <h1 style={{ fontSize: "clamp(30px,5vw,48px)", fontWeight: 900, letterSpacing: "-0.035em", margin: "0 0 16px", lineHeight: 1.05 }}>
              Terms of Service
            </h1>
            <p style={{ fontSize: 14, color: "#52525b", margin: 0 }}>
              Last updated: {LAST_UPDATED}
            </p>
          </div>

          <div style={{ background: "rgba(59,130,246,0.05)", border: "1px solid rgba(59,130,246,0.18)", borderRadius: 12, padding: "16px 20px", marginBottom: 44 }}>
            <p style={{ fontSize: 13, color: "#93c5fd", margin: 0, lineHeight: 1.7 }}>
              By using LeadScan (the &quot;Service&quot;), you agree to these terms. Please read them carefully. If you do not agree, do not use the Service.
            </p>
          </div>

          <Section title="1. Acceptance of Terms">
            <P>
              These Terms of Service (&quot;Terms&quot;) govern your access to and use of LeadScan, including the website at leadscan.app, the REST API, and the npm CLI package (&quot;leadscan&quot;). By accessing or using any part of the Service, you agree to be bound by these Terms.
            </P>
            <P>
              If you are using the Service on behalf of an organization, you represent that you have the authority to bind that organization to these Terms.
            </P>
          </Section>

          <Section title="2. Description of Service">
            <P>
              LeadScan is a company intelligence tool that fetches publicly available information from company websites, analyzes technology usage and growth signals, generates conviction scores, and optionally produces AI-generated outreach copy. The Service operates entirely on publicly accessible web data.
            </P>
          </Section>

          <Section title="3. Acceptable Use">
            <P>You agree to use the Service only for lawful purposes. You may not use the Service to:</P>
            <Ul items={[
              "Scrape, harvest, or collect data in ways that violate any website's terms of service or robots.txt directives",
              "Send unsolicited commercial messages (spam) using outreach generated by the Service",
              "Engage in any activity that violates applicable laws, including data protection and anti-spam regulations (CAN-SPAM, GDPR, CASL, etc.)",
              "Attempt to overload, disrupt, or attack the Service or any third-party systems",
              "Reverse-engineer, decompile, or attempt to extract the source code of the Service",
              "Resell or sublicense access to the Service without express written permission",
              "Use the Service to build a competing product or service",
            ]} />
            <P>
              You are solely responsible for how you use the intelligence and outreach content generated by LeadScan. AI-generated outreach is a starting point — review and comply with all applicable laws before sending any communications.
            </P>
          </Section>

          <Section title="4. Data and Privacy">
            <P>
              LeadScan only scans <strong style={{ color: "#e4e4e7" }}>publicly available</strong> information — the same data visible to anyone with a web browser. We do not access, store, or process any non-public or personal data beyond what you explicitly submit (such as a domain name or outreach prompt).
            </P>
            <P>
              We do not sell your data. For full details on what we collect and how we use it, see our{" "}
              <Link href="/privacy" style={{ color: "#93c5fd", textDecoration: "none" }}>Privacy Policy</Link>.
            </P>
          </Section>

          <Section title="5. Intellectual Property">
            <P>
              The LeadScan platform, brand, and underlying code are owned by Sripad Nadella. You are granted a limited, non-exclusive, non-transferable license to use the Service for your own business purposes.
            </P>
            <P>
              Reports and outreach content generated by LeadScan based on your inputs are yours to use. However, you may not represent AI-generated content as independently authored without disclosure where required by law.
            </P>
          </Section>

          <Section title="6. Third-Party Services">
            <P>
              The Service uses third-party APIs including Groq for AI inference. Your use of AI-powered features is also subject to{" "}
              <a href="https://groq.com/terms-of-use" target="_blank" rel="noopener noreferrer" style={{ color: "#93c5fd", textDecoration: "none" }}>
                Groq&apos;s Terms of Use
              </a>.
              We are not responsible for the availability, accuracy, or conduct of any third-party service.
            </P>
          </Section>

          <Section title="7. Disclaimers">
            <P>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
            </P>
            <Ul items={[
              "We do not guarantee that scan results are accurate, complete, or up to date — company data changes frequently.",
              "AI-generated outreach is illustrative and may contain errors — always review before sending.",
              "We do not guarantee uptime or uninterrupted access to the Service.",
              "Conviction scores are heuristic estimates, not guarantees of sales outcomes.",
            ]} />
          </Section>

          <Section title="8. Limitation of Liability">
            <P>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, LEADSCAN AND ITS OPERATORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, LOST DATA, OR BUSINESS INTERRUPTION, ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE.
            </P>
            <P>
              OUR TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING FROM THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE PAST 12 MONTHS OR (B) $10 USD.
            </P>
          </Section>

          <Section title="9. Indemnification">
            <P>
              You agree to indemnify and hold harmless LeadScan and its operators from any claims, damages, losses, or expenses (including reasonable legal fees) arising from your use of the Service, your violation of these Terms, or your violation of any third party&apos;s rights.
            </P>
          </Section>

          <Section title="10. Modifications to the Service and Terms">
            <P>
              We reserve the right to modify or discontinue the Service at any time without notice. We may update these Terms from time to time — the &quot;Last updated&quot; date at the top of this page reflects the most recent revision. Continued use of the Service after changes constitutes your acceptance of the updated Terms.
            </P>
          </Section>

          <Section title="11. Governing Law">
            <P>
              These Terms are governed by and construed in accordance with the laws of the State of California, United States, without regard to conflict of law principles. Any disputes shall be resolved in the courts located in California.
            </P>
          </Section>

          <Section title="12. Contact">
            <P>
              Questions about these Terms? Reach out at{" "}
              <a href="mailto:legal@leadscan.app" style={{ color: "#93c5fd", textDecoration: "none" }}>legal@leadscan.app</a>.
            </P>
          </Section>

          {/* Footer nav */}
          <div style={{ borderTop: "1px solid rgba(255,255,255,0.06)", paddingTop: 32, display: "flex", gap: 24, flexWrap: "wrap" }}>
            <Link href="/privacy" style={{ fontSize: 13, color: "#71717a", textDecoration: "none" }}>Privacy Policy →</Link>
            <Link href="/" style={{ fontSize: 13, color: "#71717a", textDecoration: "none" }}>Back to LeadScan →</Link>
          </div>

        </div>
      </main>
    </>
  );
}
